### ISSUE TITLE
Upgradability? 

### ISSUE THREAD

**Issue by j16sdiz** [jamesbrink/docker-postgres#11]
I am concerned with the upgradability of current setup.

To be specific:
 1. Data is stored on the image itself. If I upgrade a minor version (9.4.1 ?), I need to keep older version as a data volume. 
 2. The `firstrun` file is created under `/var/tmp`. If I use the data from other volume, it may create users / load extensions in that volume.

**Comment by jamesbrink** [comment]
@j16sdiz thank you for the input.

1.) The datadir is accessible as a data volume, I am not sure I follow you on this one.

2.) Great catch, this is not something I had considered when I first started building this out. I have been upgrading mine in production a bit funky. I will address this and update the readme, unless you wanted to open a PR for it. Thank you!
