### ISSUE TITLE
Connection Refused (May Be Elementary But Please Help)

### ISSUE THREAD

**Issue by ibanks** [jamesbrink/docker-postgres#13]
Yes I am new to docker. I believe I've tried it all at this point and do not understand why I cannot connect to the postgres database using psql. This is happening inside the actual container and outside from my host machine and it just doesn't make sense.

Inside of the container I do have this in my **postgresql.conf** file
`listen_addresses='*'`

All the settings in my **pg_hba.conf** file appear to be correct:
`local   all             postgres                                peer`
`local   all             all                                     peer`
`host    all             all             127.0.0.1/32            md5`
`host    all             all             ::1/128                 md5`
`host all  all    0.0.0.0/0  md5`

This is my /etc/hosts file:

`127.0.0.1       localhost`
`::1     localhost ip6-localhost ip6-loopback`
`fe00::0 ip6-localnet`
`ff00::0 ip6-mcastprefix`
`ff02::1 ip6-allnodes`
`ff02::2 ip6-allrouters`
`172.17.0.2      11e15d283eb2`

When I ping 172.17.0.2 from my host machine, I get a response. However, I've run 
`psql -h 172.17.0.2 -U postgres`
`psql -h 172.17.0.2`

and I get nothing but the connection refused error.

From inside the container I've run:
`psql -h localhost -U postgres`
`psql -h localhost`

and I still get nothing. The host machine port that the db container is run on is 5433. I've verified that it is connecting using netstat. What am I not getting here? Thanks in advance.

**Comment by jamesbrink** [comment]
@ibanks this is strange, which version of the postgres container are you running ?

**Comment by ibanks** [comment]
@jamesbrink I believe it is the latest version of your Postgres 9.6 image.

**Comment by ibanks** [comment]
@jamesbrink Here is what I got from running docker inspect on the image:

`
    {
        "Id": "sha256:6341c35db2effff23a321ccaf972e587d1eed2876863c38d6ec123e0fde376c3",
        "RepoTags": [
            "jamesbrink/postgres:9.6",
            "latest:latest"
        ],
        "RepoDigests": [],
        "Parent": "sha256:bb710a1a9665e93ac02e762fb420e7f27d33d3a6d42f935f376782ffebce61ac",
        "Comment": "",
        "Created": "2017-11-08T11:27:48.705588391Z",
        "Container": "b59dd480e75eb8501ea9eac64ba32ab09676eae2298627cdbcd3590dd1e8703d",
        "ContainerConfig": {
            "Hostname": "b59dd480e75e",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "POSTGRES_VERSION=9.6",
                "POSTGIS_VERSION=2.3",
                "LOCALE=en_US.UTF-8",
                "USER=postgres",
                "PASSWORD=postgres",
                "DATABASE=postgres",
                "SCHEMA=public",
                "POSTGIS=false",
                "ENCODING=SQL_ASCII",
                "BACKUP_ENABLED=false",
                "BACKUP_FREQUENCY=daily",
                "BACKUP_RETENTION=7",
                "BACKUP_EMAIL=postgres",
                "ENVIRONMENT=development"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "CMD [\"/usr/bin/supervisord\" \"-c\" \"/etc/supervisor/supervisord.conf\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:bb710a1a9665e93ac02e762fb420e7f27d33d3a6d42f935f376782ffebce61ac",
            "Volumes": {
                "/etc/postgresql": {},
                "/var/backups": {},
                "/var/lib/postgresql": {},
                "/var/log/postgresql": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "decription": "PostgreSQL Server",
                "version": "9.6"
            }
        },
        "DockerVersion": "17.09.0-ce",
        "Author": "James Brink, brink.james@gmail.com",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "5432/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "POSTGRES_VERSION=9.6",
                "POSTGIS_VERSION=2.3",
                "LOCALE=en_US.UTF-8",
                "USER=postgres",
                "PASSWORD=postgres",
                "DATABASE=postgres",
                "SCHEMA=public",
                "POSTGIS=false",
                "ENCODING=SQL_ASCII",
                "BACKUP_ENABLED=false",
                "BACKUP_FREQUENCY=daily",
                "BACKUP_RETENTION=7",
                "BACKUP_EMAIL=postgres",
                "ENVIRONMENT=development"
            ],
            "Cmd": [
                "/usr/bin/supervisord",
                "-c",
                "/etc/supervisor/supervisord.conf"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:bb710a1a9665e93ac02e762fb420e7f27d33d3a6d42f935f376782ffebce61ac",
            "Volumes": {
                "/etc/postgresql": {},
                "/var/backups": {},
                "/var/lib/postgresql": {},
                "/var/log/postgresql": {}
            },
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": [],
            "Labels": {
                "decription": "PostgreSQL Server",
                "version": "9.6"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 515491904,
        "VirtualSize": 515491904,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/ddbb62e792a6ab8b0d603d3cd3a723566307d293cfc8ec10879a9410feab55c2/diff:/var/lib/docker/overlay2/8e861412a81b2955594258ef8ac06b3706c06e63716a69ce17f2fcf2814d798e/diff:/var/lib/docker/overlay2/d1bb0d7437c3a2e20b3281a364fe33b970ad96ddf836cf3b1fef85ec5d5c12d6/diff",
                "MergedDir": "/var/lib/docker/overlay2/bd2d2247b952dd4fd4ed3b7b1c522ec9b763d3dc147ae16506193db68a649f99/merged",
                "UpperDir": "/var/lib/docker/overlay2/bd2d2247b952dd4fd4ed3b7b1c522ec9b763d3dc147ae16506193db68a649f99/diff",
                "WorkDir": "/var/lib/docker/overlay2/bd2d2247b952dd4fd4ed3b7b1c522ec9b763d3dc147ae16506193db68a649f99/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:c01c63c6823dd8a296c2134ea94d31121069f1c52f8f8789836bc7ea2e5cdc93",
                "sha256:295b3837f4dfc2cb87de98b2e1f5e5daf9b0b6c7176835f9a1c6f003454d941c",
                "sha256:70fb348e20c3b7fa90eda64ec1a4086d0abaee179d16530980c4e1561f46681b",
                "sha256:a1c082ed3abb5cd6bd4e7241ab8b224f39da6272c4c4ff60adc9d8f03d171e96"
            ]
        },
        "Metadata": {
            "LastTagTime": "2017-11-08T06:27:48.893642482-05:00"
        }
    }

`

**Comment by jamesbrink** [comment]
@ibanks I do not see a `NetworkSettings` section in your output from `docker inspect`. This might be the cause of the issue. Can you check your docker network settings? You should be able to run `docker network ls`. The default docker installation should have a bridge.

**Comment by jamesbrink** [comment]
@ibanks I know you listed some network settings in your original post but I am not sure why it is missing from this output. Can you also show me the command you are using to start the container as well as the host operating system?

**Comment by ibanks** [comment]
@jamesbrink So when I run `docker network ls` I get this:

NETWORK ID      NAME            DRIVER            SCOPE
973f23fc6c5c        bridge              bridge              local
160ea8863cba        host                host                local
3fe27270ddef        none                null                local

The host machine is my computer Ubuntu 16.04 LTS. To start the container I run:
`docker run -it -p 5433:5432 jamesbrink/postgres:9.6 /bin/bash`

The configuration I make to the container is installing vim. After that I try to run psql from inside the container then I try outside of it on my host machine.

**Comment by jamesbrink** [comment]
@ibanks sorry for the late reply have you had any luck ?
